### ISSUE TITLE
Looker Studio can't connect to the data source

### ISSUE THREAD

**Issue by GeorginaAlcaraz** [Gladior-B-V/data-hub-app#8]
I shows the error, if I try to reconnect it says that there's an error on the server, and my Data Hub doesn't load the workspace.

**Comment by zoedufrenne** [comment]
Hi @GeorginaAlcaraz, thanks for letting us know! Could you send a screenshot of the error ?

**Comment by GeorginaAlcaraz** [comment]
Sure, 
<img width="565" alt="Captura de Pantalla 2023-01-26 a la(s) 9 31 57" src="https://user-images.githubusercontent.com/123579191/214877750-f72334ca-5bda-435e-96a9-4e155db05db5.png">
<img width="650" alt="Captura de Pantalla 2023-01-26 a la(s) 9 31 29" src="https://user-images.githubusercontent.com/123579191/214877753-68c190ae-9e0d-4c92-9a04-574440e3bc1d.png">
<img width="493" alt="Captura de Pantalla 2023-01-26 a la(s) 9 30 57" src="https://user-images.githubusercontent.com/123579191/214877757-e388786b-aee2-4888-9fb7-73c5b64c5b50.png">

**Comment by zoedufrenne** [comment]
Thanks, when you log in to https://datahubapp.gladior.com with your account, can you then enter the workspace? Or do you get redirected back to the startpage?

**Comment by GeorginaAlcaraz** [comment]
No, it only shows this page, I click on workspace and it reloads on the same one.
<img width="650" alt="Captura de Pantalla 2023-01-26 a la(s) 9 31 29" src="https://user-images.githubusercontent.com/123579191/214883844-bdc8507a-2f0f-4c18-a1cc-d60fde4dc14c.png">

**Comment by zoedufrenne** [comment]
Hi @GeorginaAlcaraz, Thanks! We found the issue. Could you check if you can enter the workspace?

**Comment by GeorginaAlcaraz** [comment]
Hi, no I still can't enter my workspace

**Comment by klcem** [comment]
(sorry seeing this issue in another thread too now)
Hi @zoedufrenne I'm having the same issue. Then, when I enter the workspace on https://datahubapp.gladior.com/ it looks like this:

![Screen Shot 2023-03-22 at 12 23 14 PM](https://user-images.githubusercontent.com/128624036/226971433-c4bd6a47-059b-4a19-a5c9-a1339470bfc8.png)

**Comment by zoedufrenne** [comment]
Hi @klcem , can you share your data hub id with us? We'll check if we can see what kind of issue this is. Data hub id is found at your profile. You can click on your name in the right corner and select 'Edit profile'. There you see the Data Hub ID.

**Comment by klcem** [comment]
Hi @zoedufrenne, here it is: google_117707451940068907790

**Comment by Madda17** [comment]
Hello! I'm having the same problem right now, should I open a new issue?

![image](https://user-images.githubusercontent.com/129771123/229551310-ed240e1d-33e0-4948-8a92-922b75731b71.png)

**Comment by zoedufrenne** [comment]
Hi @Madda17 & @GeorginaAlcaraz, We've made an update to the Data Hub. Can you let us know if the error is still there?

**Comment by Madda17** [comment]
> Hi @Madda17 & @GeorginaAlcaraz, We've made an update to the Data Hub. Can you let us know if the error is still there?

My bug is solved! I could create a new data source and use it on a report. Thank you very much!

**Comment by klcem** [comment]
Hi @zoedufrenne, I am still having the connecting issue using a google business email - but it works fine with a regular gmail. I'm just using gmail for now, but figured I'd let you know.

**Comment by zoedufrenne** [comment]
@klcem thanks for letting us know. Your issue is still on our list. It will take us some time to enhance the data hub where you can use google business accounts with the GBP connector!

**Comment by hiviz** [comment]
I'm also running into the same issue:
> https://capture.dropbox.com/Rpy72PxQVlFfXpjo
> https://capture.dropbox.com/Gm3SlStyCK7jz7pA

Please advise.

**Comment by rkooiker** [comment]
@hiviz we will look into this in the future.

**Comment by Harheeni** [comment]
HI , im having the connection issue for past 3 days, i dont  know what to do,i need help please
![Screenshot 2024-07-30 112233](https://github.com/user-attachments/assets/a316c0b1-28c5-4ee9-971e-2511ec9b9f17)

**Comment by rkooiker** [comment]
@Harheeni please reply with your Data Hub account id so that we can look further into the issue.
